### ISSUE TITLE
about networked_controllers,error: can't copy 'resource/networked_controllers': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by rk10012** [10varun17/multi-agent-robotics-controllers#1]
Starting >>> multi_agent_task_mgmt
Starting >>> agents
Starting >>> launch_multi_agent
Starting >>> leader_follower
Starting >>> networked_controllers
Starting >>> transformations
Finished <<< launch_multi_agent [0.56s]                                        
Finished <<< multi_agent_task_mgmt [0.71s]                                  
Starting >>> formation_controller
Finished <<< transformations [1.02s]                                          
Finished <<< leader_follower [1.02s]
Finished <<< agents [1.04s]
--- stderr: networked_controllers
error: can't copy 'resource/networked_controllers': doesn't exist or not a regular file
---
Failed   <<< networked_controllers [1.05s, exited with code 1]
Aborted  <<< formation_controller [0.43s]                     

Summary: 5 packages finished [1.25s]
  1 package failed: networked_controllers
  1 package aborted: formation_controller
  1 package had stderr output: networked_controllers
  
  how can i solve it?

**Comment by 10varun17** [comment]
Thanks for pointing this out. A required sub-directory `resource` was missing in `networked_controllers` package. It's now fixed and should build successfully.

**Comment by 10varun17** [comment]
@ran-zhao Does it work now? Could you give me a confirmation please?
